from typing import TypedDict

class SunState(TypedDict, total=False):
    user_query: str
    request_id: str
    city: str
    skin_type: int
    body_area: int
    age: int
    plan: list[str]
    current_agent: str
    completed_agents: list[str]
    trace: list[dict]
    verification_attempts: int
    verification_status: str
    verification_issues: list[str]
    intent: str
    route_reason: str
    latitude: float
    longitude: float
    country: str
    temperature: float
    uv_index: float
    cloud_cover: int
    relative_humidity: int
    wind_speed: float
    weather_code: int
    hourly_forecast: list
    uv_level: str
    protection_required: bool
    heat_caution: str
    overall_action: str
    safety_reasons: list[str]
    protective_actions: list[str]
    hard_stop: bool
    evidence: list[dict]
    evidence_summary: list[str]
    evidence_status: str
    retrieval_backend: str
    retrieval_query: str
    retrieval_count: int
    best_time: str
    decision_score: float
    decision_basis: list[str]
    explanation: str
